export const USER_SEARCH_USER_REQUEST = 'USER_SEARCH_USER_REQUEST';
export const USER_SEARCH_USER_SUCCESS = 'USER_SEARCH_USER_SUCCESS';
export const USER_SEARCH_USER_FAILED = 'USER_SEARCH_USER_FAILED';

export const USER_GET_SINGLE_USER_REQUEST = 'USER_GET_SINGLE_USER_REQUEST';
export const USER_GET_SINGLE_USER_SUCCESS = 'USER_GET_SINGLE_USER_SUCCESS';
export const USER_GET_SINGLE_USER_FAILED = 'USER_GET_SINGLE_USER_FAILED';

export const USER_UPDATE_INFO_REQUEST = 'USER_UPDATE_INFO_REQUEST';
export const USER_UPDATE_INFO_SUCCESS = 'USER_UPDATE_INFO_SUCCESS';
export const USER_UPDATE_INFO_FAILED = 'USER_UPDATE_INFO_FAILED';

export const USER_UPDATE_WALLPAPER_REQUEST = 'USER_UPDATE_WALLPAPER_REQUEST';
export const USER_UPDATE_WALLPAPER_SUCCESS = 'USER_UPDATE_WALLPAPER_SUCCESS';
export const USER_UPDATE_WALLPAPER_FAILED = 'USER_UPDATE_WALLPAPER_FAILED';

export const USER_UPDATE_AVATAR_REQUEST = 'USER_UPDATE_AVATAR_REQUEST';
export const USER_UPDATE_AVATAR_SUCCESS = 'USER_UPDATE_AVATAR_SUCCESS';
export const USER_UPDATE_AVATAR_FAILED = 'USER_UPDATE_PROFILE_FAILED';

export const USER_VERIFICATION_REQUEST = 'USER_VERIFICATION_REQUEST';
export const USER_VERIFICATION_SUCCESS = 'USER_VERIFICATION_SUCCESS';
export const USER_VERIFICATION_FAILED = 'USER_VERIFICATION_FAILED';

export const USER_CHECK_USERNAME_REQUEST = 'USER_CHECK_USERNAME_REQUEST';
export const USER_CHECK_USERNAME_SUCCESS = 'USER_CHECK_USERNAME_SUCCESS';
export const USER_CHECK_USERNAME_FAILED = 'USER_CHECK_USERNAME_FAILED';

export const USER_CHECK_EMAIL_REQUEST = 'USER_CHECK_EMAIL_REQUEST';
export const USER_CHECK_EMAIL_SUCCESS = 'USER_CHECK_EMAIL_SUCCESS';
export const USER_CHECK_EMAIL_FAILED = 'USER_CHECK_EMAIL_FAILED';

export const USER_REIGISTER_REQUEST = 'USER_REIGISTER_REQUEST';
export const USER_REIGISTER_SUCCESS = 'USER_REIGISTER_SUCCESS';
export const USER_REIGISTER_FAILED = 'USER_REIGISTER_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
