export const FOLLOWER_GET_ALL_YOU_FAN_OF_REQUEST =
  'FOLLOWER_GET_ALL_YOU_FAN_OF_REQUEST';
export const FOLLOWER_GET_ALL_YOU_FAN_OF_SUCCESS =
  'FOLLOWER_GET_ALL_YOU_FAN_OF_SUCCESS';
export const FOLLOWER_GET_ALL_YOU_FAN_OF_FAILED =
  'FOLLOWER_GET_ALL_YOU_FAN_OF_FAILED';

export const FOLLOWER_GET_ALL_REQUEST = 'FOLLOWER_GET_ALL_REQUEST';
export const FOLLOWER_GET_ALL_SUCCESS = 'FOLLOWER_GET_ALL_SUCCESS';
export const FOLLOWER_GET_ALL_FAILED = 'FOLLOWER_GET_ALL_FAILED';

export const FOLLOWER_COUNT_YOUR_FANS_REQUEST =
  'FOLLOWER_COUNT_YOUR_FANS_REQUEST';
export const FOLLOWER_COUNT_YOUR_FANS_SUCCESS =
  'FOLLOWER_COUNT_YOUR_FANS_SUCCESS';
export const FOLLOWER_COUNT_YOUR_FANS_FAILED =
  'FOLLOWER_COUNT_YOUR_FANS_FAILED';

export const FOLLOWER_COUNT_FANS_REQUEST = 'FOLLOWER_COUNT_FANS_REQUEST';
export const FOLLOWER_COUNT_FANS_SUCCESS = 'FOLLOWER_COUNT_FANS_SUCCESS';
export const FOLLOWER_COUNT_FANS_FAILED = 'FOLLOWER_COUNT_FANS_FAILED';

export const FOLLOWER_CHECK_IF_FAN_OF_REQUEST =
  'FOLLOWER_CHECK_IF_FAN_OF_REQUEST';
export const FOLLOWER_CHECK_IF_FAN_OF_SUCCESS =
  'FOLLOWER_CHECK_IF_FAN_OF_SUCCESS';
export const FOLLOWER_CHECK_IF_FAN_OF_FAILED =
  'FOLLOWER_CHECK_IF_FAN_OF_FAILED';

export const FOLLOWER_BE_FAN_OR_REMOVE_REQUEST =
  'FOLLOWER_BE_FAN_OR_REMOVE_REQUEST';
export const FOLLOWER_BE_FAN_OR_REMOVE_SUCCESS =
  'FOLLOWER_BE_FAN_OR_REMOVE_SUCCESS';
export const FOLLOWER_BE_FAN_OR_REMOVE_FAILED =
  'FOLLOWER_BE_FAN_OR_REMOVE_FAILED';
