export const COMMENT_GET_TOP_TALKS_REQUEST = 'COMMENT_GET_TOP_TALKS_REQUEST';
export const COMMENT_GET_TOP_TALKS_SUCCESS = 'COMMENT_GET_TOP_TALKS_SUCCESS';
export const COMMENT_GET_TOP_TALKS_FAILED = 'COMMENT_GET_TOP_TALKS_FAILED';

export const COMMENT_POST_DELETE_REQUEST = 'COMMENT_POST_DELETE_REQUEST';
export const COMMENT_POST_DELETE_SUCCESS = 'COMMENT_POST_DELETE_SUCCESS';
export const COMMENT_POST_DELETE_FAILED = 'COMMENT_POST_DELETE_FAILED';

export const COMMENT_POST_EDIT_REQUEST = 'COMMENT_POST_EDIT_REQUEST';
export const COMMENT_POST_EDIT_SUCCESS = 'COMMENT_POST_EDIT_SUCCESS';
export const COMMENT_POST_EDIT_FAILED = 'COMMENT_POST_EDIT_FAILED';

export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILED = 'COMMENT_POST_FAILED';
