export const PHOTOS_CREATE_ALBUM_REQUEST = 'PHOTOS_CREATE_ALBUM_REQUEST';
export const PHOTOS_CREATE_ALBUM_SUCCESS = 'PHOTOS_CREATE_ALBUM_SUCCESS';
export const PHOTOS_CREATE_ALBUM_FAILED = 'PHOTOS_CREATE_ALBUM_FAILED';
export const PHOTOS_CLEAR_ALBUM = 'PHOTOS_CLEAR_ALBUM';

export const PHOTOS_GET_BY_ALBUM_REQUEST = 'PHOTOS_GET_BY_ALBUM_REQUEST';
export const PHOTOS_GET_BY_ALBUM_SUCCESS = 'PHOTOS_GET_BY_ALBUM_SUCCESS';
export const PHOTOS_GET_BY_ALBUM_FAILED = 'PHOTOS_GET_BY_ALBUM_FAILED';
