export const POST_FIND_ALL_POST_OF_YOU_FAN_REQUEST =
  'POST_FIND_ALL_POST_OF_YOU_FAN_REQUEST';
export const POST_FIND_ALL_POST_OF_YOU_FAN_SUCCESS =
  'POST_FIND_ALL_POST_OF_YOU_FAN_SUCCESS';
export const POST_FIND_ALL_POST_OF_YOU_FAN_FAILED =
  'POST_FIND_ALL_POST_OF_YOU_FAN_FAILED';

export const POST_COUNT_ALL_REQUEST = 'POST_COUNT_ALL_REQUEST';
export const POST_COUNT_ALL_SUCCESS = 'POST_COUNT_ALL_SUCCESS';
export const POST_COUNT_ALL_FAILED = 'POST_COUNT_ALL_FAILED';

export const POST_EDIT_BODY_REQUEST = 'POST_EDIT_BODY_REQUEST';
export const POST_EDIT_BODY_SUCCESS = 'POST_EDIT_BODY_SUCCESS';
export const POST_EDIT_BODY_FAILED = 'POST_EDIT_BODY_FAILED';

export const POST_DELETE_PHOTO_REQUEST = 'POST_DELETE_PHOTO_REQUEST';
export const POST_DELETE_PHOTO_SUCCESS = 'POST_DELETE_PHOTO_SUCCESS';
export const POST_DELETE_PHOTO_FAILED = 'POST_DELETE_PHOTO_FAILED';

export const POST_DELETE_AND_PHOTOS_REQUEST = 'POST_DELETE_AND_PHOTOS_REQUEST';
export const POST_DELETE_AND_PHOTOS_SUCCESS = 'POST_DELETE_AND_PHOTOS_SUCCESS';
export const POST_DELETE_AND_PHOTOS_FAILED = 'POST_DELETE_AND_PHOTOS_FAILED';

export const POST_GET_SINGLE_REQUEST = 'POST_GET_SINGLE_REQUEST';
export const POST_GET_SINGLE_SUCCESS = 'POST_GET_SINGLE_SUCCESS';
export const POST_GET_SINGLE_FAILED = 'POST_GET_SINGLE_FAILED';

export const POST_GET_ALL_REQUEST = 'POST_GET_ALL_REQUEST';
export const POST_GET_ALL_SUCCESS = 'POST_GET_ALL_SUCCESS';
export const POST_GET_ALL_FAILED = 'POST_GET_ALL_FAILED';

export const POST_PHOTOS_REQUEST = 'POST_PHOTOS_REQUEST';
export const POST_PHOTOS_SUCCESS = 'POST_PHOTOS_SUCCESS';
export const POST_PHOTOS_FAILED = 'POST_PHOTOS_FAILED';

export const POST_CANCEL_PHOTOS_REQUEST = 'POST_CANCEL_PHOTOS_REQUEST';
export const POST_CANCEL_PHOTOS_SUCCESS = 'POST_CANCEL_PHOTOS_SUCCESS';
export const POST_CANCEL_PHOTOS_FAILED = 'POST_CANCEL_PHOTOS_FAILED';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED';
